AjuntamentdeBarcelona/decidim-barcelona

- .rubocop.yml
- db/schema.rb
This adds the missing database schema for this app.
*None*
*None*
*None*
> Add missing schema

- .rubocop.yml
- app/views/layouts/decidim/_logo.html.erb
- config/initializers/carrierwave.rb
- config/secrets.yml
This adds changes needed for the deployment of this app to properly work.
*None*
*None*
*None*
> Deployment adjustments

- config/secrets.yml
This fixes the `secrets.yml` file mistakenly merged on the previous PR (https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/11)
*None*
*None*
*None*
> Fix social networks

- Gemfile.lock
Upgrade decidim to get nice new features.
*None*
*None*
*None*
> Upgrade decidim

- config/environments/production.rb
This enforces using SSL on production.
*None*
*None*
*None*
> Force ssl on production

- Gemfile
- Gemfile.lock
- Procfile
- config/environments/production.rb
- config/puma.rb
- config/routes.rb
- config/sidekiq.yml
This adds sidekiq as a background job processor.
*None*
*None*
*None*
> Add sidekiq

- lib/tasks/import_proposals.rake
Import proposal answers from old Decidim.
> Import proposal answers

- lib/tasks/import_attachments.rake
- lib/tasks/import_meeting_attachments.rake
Several improvements to the importers.
*None*
*None*
*None*
> Improve importers

- config/routes.rb
This adds leagacy redirects to conform with the new version.
*None*
*None*
*None*
> Add redirects

- app/services/census_authorization_handler.rb
- app/views/census_authorization/_form.html.erb
- config/locales/ca.yml
- config/locales/es.yml
- spec/services/census_authorization_handler_spec.rb
This adds the scope to authorization handler and makes sure we store it.
*None*
*None*
*None*
*None*
> Add scope to authorization handler

- app/services/census_authorization_handler.rb
- app/views/census_authorization/_form.html.erb
- config/locales/ca.yml
- config/locales/es.yml
- spec/services/census_authorization_handler_spec.rb
This improves authorization by adding a date select instead of an HTML5 field. 
*None*
*None*
*None*
> Improve authorization

- README.md
Add Docker instructions to README.
> Add development environment instructions to README

- config/locales/ca.yml
- config/locales/es.yml
- Fixes https://github.com/AjuntamentdeBarcelona/decidim-barcelona/issues/49
> Add missing invalid district locale

- Gemfile
- Gemfile.lock
- config/environments/production.rb
This adds a redirection when accessing the website via `www`.
*None*
*None*
*None*
> Add redirection to hosts with www

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/environments/production.rb
> Add lograge for json logs

- Gemfile
- Gemfile.lock
- app.json
- config/initializers/carrierwave.rb
- config/initializers/decidim.rb
- db/seeds.rb
Fix review apps. Seed and set the correct host for the organization.
None
> Fix review apps

- engines/decidim-debates/app/views/decidim/debates/admin/debates/_form.html.erb
- engines/decidim-debates/app/views/decidim/debates/admin/debates/edit.html.erb
- engines/decidim-debates/app/views/decidim/debates/admin/debates/index.html.erb
- engines/decidim-debates/app/views/decidim/debates/admin/debates/new.html.erb
- engines/decidim-debates/spec/shared/manage_debates_examples.rb
> New admin style for debates

- db/migrate/20170405084212_fix_email_uniqueness_index.rb
- db/schema.rb
Fix uniqueness index to allow registration of users with the same email from multiple organizations.
*None*
*None*
*None*
> Fix uniqueness index

- app.json
This tests `heroku-16` stack.
*None*
*None*
*None*
> Test heroku-16 stack

- lib/tasks/migrate_results_to_accountability.rake
This PR fixes the migration task that moves results from Decidim::Results to Decidim::Accountability
Unexpected
> Fix migration task

- Gemfile
- Gemfile.lock
Add `decidim-assemblies`.
*None*
*None*
*None*
> Add assemblies

- db/migrate/20170315082560_add_available_authorizations_to_organization.decidim.rb
Fix migration that breaks on deployment time (not in production).
* Related to: https://github.com/decidim/decidim/pull/2097
*None*
*None*
*None*
> Fix migration handlers

- decidim-debates/app/controllers/decidim/debates/admin/debates_controller.rb
- decidim-debates/app/views/decidim/debates/admin/debates/_form.html.erb
Lets `decidim-debates` work with assemblies.
- Fixes #127, #173
Notice I'm using a test assembly and it works fine.
> Make debates work with assemblies

- Gemfile
- Gemfile.lock
Update initiatives to a branch that fixes some issues found on production.
*None*
*None*
*None*
*None*
> Use initiatives branch

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/environments/staging.rb
- config/initializers/carrierwave.rb
- config/secrets.yml
Prepares the app for a staging environment.
Subtasks:
- Related to #186.
> Add staging environment

- Gemfile
- Gemfile.lock
- db/migrate/20180212140623_create_decidim_module_sortitions_sortitions.decidim_sortitions.rb
- db/migrate/20180212140624_add_witnesses_to_sortitions.decidim_sortitions.rb
- db/migrate/20180212140625_add_additional_info_to_sortitions.decidim_sortitions.rb
- db/migrate/20180212140626_add_author_to_sortitions.decidim_sortitions.rb
- db/migrate/20180212140627_add_reference_to_sortitions.decidim_sortitions.rb
- db/migrate/20180212140628_add_title_to_sortition.decidim_sortitions.rb
- db/migrate/20180212140629_drop_decidim_category_id_from_sortitions.decidim_sortitions.rb
- db/migrate/20180212140630_add_cancel_data_to_sortition.decidim_sortitions.rb
- db/migrate/20180212140631_make_sortition_reference_nullable.decidim_sortitions.rb
- db/migrate/20180212140632_add_candidate_proposals_to_sortitions.decidim_sortitions.rb
- db/migrate/20180212140633_rename_sortitions_table.decidim_sortitions.rb
- db/schema.rb
Adds [decidim-sortitions](https://github.com/decidim/decidim-module-sortitions) to the project.
*None*
*None*
*None*
*None*
> Add sortitions

- Gemfile
- Gemfile.lock
Use the accountability branch with display fixes needed to release the PAM results.
*None*
*None*
*None*
*None*
> Use fixed accountability branch

- db/migrate/20181008075953_move_organization_fields_to_hero_content_block.decidim.rb
> Fix migration

- config/routes.rb
`Decidim::Accountability::Result` does not have any `extra` column, so we need to handle this case.
- Related to https://sentry.io/share/issue/4eabe3b5d23d4c1e981e8d2dba64bcf3/
None
> Fix action_plan routes

- app/services/sms_gateway.rb
- config/initializers/decidim.rb
- config/locales/ca.yml
- config/locales/en.yml
- config/locales/es.yml
- config/secrets.yml
- spec/services/sms_gateway_spec.rb
Adds the SMS service so we can send the messages and let user be verified by SMS.
> Add SMS gateway service

- config/initializers/carrierwave.rb
> Set amazon S3 region to Paris.

- Gemfile.lock
- db/migrate/20200211144500_add_user_group_author_to_blogs.decidim_blogs.rb
- db/schema.rb
This PR updates decidim-barcelona to latest Decidim to incorporate the bugfix in https://github.com/decidim/decidim/pull/5698
- Fixes #?
> Avoid user_manager permissions to shadow space admin permissions

- app/assets/stylesheets/decidim/email.css
Fix format typo errors in _email.css_ as reported by codeclimate.
There are still "best practice" codeclimate indications to be solved
- Fixes #287
> Fix codeclimate css test

- Gemfile.lock
- db/schema.rb
This commit will include bugfixes for jira 74 and 76:
- https://github.com/decidim/decidim/pull/5707
- https://github.com/decidim/decidim/pull/5705
> Upgrade to latest Decidim to include bugfixes

- Gemfile
- Gemfile.lock
- db/migrate/20200318164332_create_decidim_term_customizer_translation_sets.decidim_term_customizer.rb
- db/migrate/20200318164333_create_decidim_term_customizer_translations.decidim_term_customizer.rb
- db/migrate/20200318164334_create_decidim_term_customizer_constraints.decidim_term_customizer.rb
- db/schema.rb
This PR updates the Decidim gem in order to provide the fix in https://github.com/decidim/decidim/pull/5853
- Related to https://github.com/decidim/decidim/pull/5853
> Intoduce term-customizer and port latest bugfix for relative path in mentioned proposal email

- Gemfile.lock
- ISSUE_TEMPLATE.md
Upgrade decidim gem to get the visible_meeting_for scope fixe
- Fixes #?
> Upgrade Decidim 0.22 with fix for visible_meeting_for scope

- config/initializers/carrierwave.rb
Change AWS S3 region and bucket to new ones.
> Change aws region

- app/cells/census_authorization_metadata_cell.rb
- config/initializers/decidim.rb
- config/locales/ca.yml
- config/locales/es.yml
- db/schema.rb
Add the census authorization metadata cell for participants that can renew verifications (available on **Decidim 0.22**) 
- Related to https://github.com/decidim/decidim/pull/5854
> Add census authorization metadata cell

- Gemfile.lock
- db/migrate/20210303083722_invalidate_all_sessions_for_deleted_users.decidim.rb
- db/schema.rb
Updates decidim to latest 0.23 version.
> Update to latest 0.23

- Gemfile.lock
- db/migrate/20210319081722_fix_answered_proposals_after_copy.decidim_proposals.rb
- db/migrate/20210319081723_fix_counters_for_copied_proposals.decidim_proposals.rb
- db/schema.rb
Updates to the latest version to get some bigfixes.
> Update to latest decidim 0.23

- Gemfile
- Gemfile.lock
- db/migrate/20210422132731_create_decidim_navigation_maps_blueprints.decidim_navigation_maps.rb
- db/migrate/20210422132732_add_title_to_navigation_maps_blueprints.decidim_navigation_maps.rb
- db/migrate/20210422132733_create_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422132734_add_link_type_to_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422132735_add_area_id_to_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422132736_add_color_to_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422132737_add_reference_to_content_block_to_blueprints_table.decidim_navigation_maps.rb
- db/migrate/20210422132738_add_height_to_navigation_maps_blueprints.decidim_navigation_maps.rb
- db/schema.rb
This PR adds the navigation map module to preprod.
> Add navigation map module

- Gemfile
- Gemfile.lock
- db/migrate/20210422134754_create_decidim_navigation_maps_blueprints.decidim_navigation_maps.rb
- db/migrate/20210422134755_add_title_to_navigation_maps_blueprints.decidim_navigation_maps.rb
- db/migrate/20210422134756_create_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422134757_add_link_type_to_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422134758_add_area_id_to_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422134759_add_color_to_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
- db/migrate/20210422134760_add_height_to_navigation_maps_blueprints.decidim_navigation_maps.rb
- db/schema.rb
Install https://github.com/Platoniq/decidim-module-navigation_maps
> Install navigation maps module

- app/views/decidim/accountability/results/_home_scopes.html.erb
> order by scope code

- .gitignore
- config/secrets.yml
- lib/tasks/budget_stats.rake
> add rake task to extract stats from verifications from a budgets component

- config/initializers/initiatives.rb
- spec/system/initiatives_spec.rb
This PR enables the creation of initiatives, reverting #378 
- Related to #378
> Re-enable initiatives creation

- config/sidekiq.yml
Add sidekiq new queues based on the changelog for the upgrade to Decidim 0.25
> Add exports and translations queues to sidekiq

- Gemfile.lock
Includes the PRs below:
- https://github.com/AjuntamentdeBarcelona/decidim/pull/25
- https://github.com/AjuntamentdeBarcelona/decidim/pull/26
- https://github.com/AjuntamentdeBarcelona/decidim/pull/28
- https://github.com/AjuntamentdeBarcelona/decidim/pull/29
> Update decidim version to revision 4a3fb9e

- app/services/concerns/decidim/accountability/results_calculator_override.rb
Fix: super method for Override concern fixed. It was added an alias_method instead.
> fix: add alias_method for progress fix/result_calculator_override

- app/views/decidim/accountability/results/home.html.erb
NOT FOR MERGE!
This change is a temporal change in the pre-production environment
> Show results for barribarceloneta

- app/views/decidim/accountability/results/home.html.erb
New env variable to dynamically select the participatory spaces in which we want to show the results
> Show accountability results env variable

- app/cells/decidim/budgets/project_list_item/project_data.erb
Fix error:
```
ActionView::Template::Error: Template missing: view: `project_data_vote_button.erb`
```
> Fix project vote button

- app/cells/concerns/decidim/activities_cell_override.rb
- app/cells/concerns/decidim/content_blocks/last_activity_cell_override.rb
- config/initializers/decidim_overrides.rb
- spec/lib/overrides_spec.rb
The last activity content block and activities cell get all components without taking into account if these components are published or not
> Last Activities and not published components

- app/cells/concerns/decidim/activities_cell_override.rb
- app/cells/concerns/decidim/content_blocks/last_activity_cell_override.rb
Fix error `ActionView::Template::Error (undefined method published? for nil:NilClass)` for last activities overrides
> Fix last activities for nil components

- Gemfile.lock
Updates decidim including some of the fixes for DECIDIM-758
- Fixes DECIDIM-753 ([commit](https://github.com/AjuntamentdeBarcelona/decidim/pull/34/commits/d15f586c36abf87ec2bd2e6709d71b15b6c5888d))
- Fixes https://github.com/decidim/decidim/issues/11471
- Fixes https://github.com/decidim/decidim/issues/11469
- Fixes https://github.com/decidim/decidim/issues/11464
- Fixes https://github.com/decidim/decidim/issues/11467
> Update decidim version to revision 4315d47

- babel.config.json
Fix Heroku deployment by removing unused Babel configurations
> Fix babel.config.json

- Gemfile.lock
Upgrade Decidim version including a revert of this commit: https://github.com/decidim/decidim/commit/695c85f7
- Related to https://github.com/decidim/decidim/issues/11964
- Fixes #505
> Bump decidim version

- app/cells/concerns/decidim/user_profile_cell_override.rb
- config/initializers/decidim_overrides.rb
- spec/lib/overrides_spec.rb
Return empty URL for profile path if user nickname is blank
- Fixes #507
> Return empty URL for profile path if user nickname is blank

- Gemfile
- Gemfile.lock
Update `decidim-decidim_awesome` to include the fix for this issue: https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/266
> Bump decidim-decidim_awesome version

- app/cells/census_sarria_sant_gervasi_authorization_metadata_cell.rb
- app/services/census_sarria_sant_gervasi_authorization_handler.rb
- app/views/census_sarria_sant_gervasi_authorization/_form.html.erb
- config/initializers/decidim.rb
- config/locales/ca.yml
- config/locales/es.yml
- spec/services/census_sarria_sant_gervasi_authorization_handler_spec.rb
- spec/system/census_sarria_sant_gervasi_authorization_spec.rb
Add new authorization for users from Sarria-Sant Gervasi
> Add authorization for Sarria-Sant Gervasi census

- Gemfile.lock
Bump decidim version including a bugfix related to initiatives and scopes.
- Related to https://github.com/decidim/decidim/pull/13598
> Bump decidim from `739d2cc` to `4bfc73b`

- .github/workflows/test.yml
- .github/workflows/test_census_sms.yml
- .github/workflows/test_stats.yml
- Gemfile
- Gemfile.lock
- Rakefile
Bump decidim version including some official backports for bugfixes. 
> ⚠️ We need to include this buildpack in Heroku while deploying these changes: `https://github.com/RohanDebroy/heroku-buildpack-wkhtmltopdf.git`
- Related to https://github.com/decidim/decidim/pull/13606
- Related to https://github.com/decidim/decidim/pull/13609
- Related to https://github.com/decidim/decidim/pull/13622
- Related to https://github.com/decidim/decidim/pull/13629
- Related to https://github.com/decidim/decidim/pull/13608
- Related to https://github.com/decidim/decidim/pull/13637
- Related to https://github.com/decidim/decidim/pull/13641
- Related to https://github.com/decidim/decidim/pull/13621
- Related to https://github.com/decidim/decidim/pull/13647
- Related to …
> Bump decidim from `4bfc73b` to `f3b1252`

- Gemfile
- Gemfile.lock
Install AppSignal and uninstall Scout APM as there were conflicts between them
> Install AppSignal

- app/lib/decidim/overrides/proposals/proposal_serializer.rb
- config/initializers/decidim_overrides.rb
- spec/lib/overrides_spec.rb
Fix proposals export error with deleted users
- Related to https://github.com/decidim/decidim/pull/13592
> Fix proposals export error with deleted users

- .github/workflows/test.yml
- .github/workflows/test_census_sms.yml
- .github/workflows/test_stats.yml
> Update apt before installing on workflows

- README.md
- lib/tasks/change_merged_proposal_authors.rake
- lib/tasks/change_proposal_category.rake
New rake task to change proposal category.
Usage:
```bash
bundle exec rake decidim:change_proposal_category[proposal_id,category_id]
```
> New rake task to change proposal category

- .codeclimate.yml
- app/packs/src/decidim/index.js
- spec/lib/overrides_spec.rb
Comment the funcionality of remote tooltips, since we are having some issue on performance, and those remote calls are increasing the connections per visit.
This is a file overriden from the decidim application.
> Disable usage of remote tooltip calls

- Gemfile
- Gemfile.lock
Temporary uninstall `decidim-kids` module.
> Temporary uninstall `decidim-kids` module

- config/locales/ca.yml
- config/locales/es.yml
Fix date time input format
- Related to https://github.com/decidim/decidim/issues/14312
> Change date format order for Spanish and Catalan

- Gemfile
- Gemfile.lock
Add necessary gems to deploy decidim-barcelona using capistrano
> Add capistrano gems

- config/initializers/wicked_pdf.rb
Force WickedPdf not to use sprockets
> Custom WickedPdf initializer

- Gemfile
- Gemfile.lock
- config/schedule.rb
Install [whenever](https://github.com/javan/whenever) to manage cron jobs
> Install whenever to manage cron jobs

- config/environments/production.rb
> Add Redis as cache store

- Gemfile
- Gemfile.lock
Bump decidim version including a change to generate a random nickname for ephemeral users
> Bump decidim version from `18b810a` to `c41a526`

- Gemfile.lock
Bump decidim version including this change: https://github.com/AjuntamentdeBarcelona/decidim/pull/57
> Bump decidim from `c41a526` to `02319fa`
