AjuntamentdeBarcelona/decidim-barcelona

config/secrets.yml

I added omniauth omniauth credentials to secrets. They must be defined as a env variables into the server.
- Related to https://github.com/AjuntamentdeBarcelona/decidim/pull/515
None
None
None

Add omniauth secrets configuration

---

engines/decidim-debates/app/views/decidim/debates/debates/index.html.erb
engines/decidim-debates/app/views/decidim/debates/debates/show.html.erb

This fixes the debates' layout by removing the unneeded `wrapper`.
*None*
*None*
*None*

Fix debates layout

---

Dockerfile

The Docker image wasn't building because a problem with the locales and bundle install was failing.
- Fixes #44

Fix Dockerfile to work with decidim-debates

---

app/views/pages/home/_extended.html.erb
config/locales/ca.yml
config/locales/es.yml

The debates explanation on home page was the same as meetings. I also fixed the broken "faq" page link to "more-information" page.
- Fixes #52 
- Fixes #33 
None

Fix debate explanation text and faq link

---

config/environments/production.rb

Reduce logger verbosity by switching from `:debug` (strangely a default on rails 5) to `:info`.
*None*
*None*
*None*

Reduce logger verbosity

---

Procfile

This forces passenger's instance to be fixed to 5 (or configurable with WEB_CONCURRENCY) so resource usage is stable and predictable, and also to keep response times lower (as it doesn't have to spawn new processes).
*None*
*None*
*None*

Make sure passenger spawns up 5 instances to keep the app hot

---

config/initializers/decidim.rb

Add missing configuration property to `geocoder`.
None
None
None
None

Add missing property to geocoder config

---

Gemfile
Gemfile.lock
config/environments/production.rb

Remove hardcoded redirections since they are handled dynamically since https://github.com/AjuntamentdeBarcelona/decidim/pull/1075
- Related to https://github.com/AjuntamentdeBarcelona/decidim/pull/1075
None

Remove redirection

---

config/environments/production.rb

Sometimes we find missing translation texts. While we fix these missing translations, we will fallback to English to at least not show an ugly unescaped HTML dump.
None
None

Fallback to English in production when missing i18n

---

app/controllers/decidim_controller.rb
config/secrets.yml

This adds context to our Sentry error reports.

Add Raven context

---

README.md

Fix Markdown syntax so that the logo in the README file is properly shown.
None
None

Fix logo in README file

---

Gemfile.lock
config/locales/ca.yml
config/locales/es.yml

This is a temporary fix until `Decidim` fixes this missing translation. 
- Related to https://github.com/AjuntamentdeBarcelona/decidim/issues/1191

Add missing projects & proposals locales

---

.travis.yml

Execute the `bundle install` command only once, thus shortening TravisCI build time several minutes.
None
None

Install bundler deps only once

---

config/routes.rb

Redirects to `/404` when the slug is not found in the organization processes.
- Fixes #96 
None

Show 404 when process slug is not valid

---

config/environments/development.rb
engines/decidim-debates/app/models/decidim/debates/debate.rb
engines/decidim-debates/config/i18n-tasks.yml
engines/decidim-debates/config/locales/ca.yml
engines/decidim-debates/config/locales/es.yml
engines/decidim-debates/lib/decidim/debates/feature.rb
engines/decidim-debates/spec/factories.rb
engines/decidim-debates/spec/features/comments_spec.rb

We had reports of failures when trying to send a notification email when a comment was replied on a debate. I found out that `debates` was not using the `Resourceable` module, so the email was failing to generate a needed URL and was not being delivered.
This PR fixes this issue and adds some missing locales in the admin section.
None
None

Fix comments for debates

---

app/services/decidim_legacy_routes.rb
config/routes.rb

We had a couple of old URL which didn't redirect properly on production. I found out that we were missing a `process` route without `step_id`, so this PR adds a `DecidimLegacyUrl` class that should fix most of the related cases. 
- Fixes #111

Fix broken old URLs issue.

---

config/routes.rb

Looks like the constraint we were using was obsolete since the host it's `www.decidim.barcelona`, this PR updates the constraint with a RegExp to match the host properly.
- Fixes #111

Update the routes constraint to fix old broken urls.

---

Gemfile
Gemfile.lock
config/environments/production.rb

This allows skipping certain hosts when forcing SSL with the end goal of proxying the sites from the outside.
*None*
*None*
*None*

Don't enforce ssl on certain hosts

---

config/routes.rb

This fixes a `LocalJump` exception in routes, since we're using blocks and `return` is invalid.
*None*
*None*
*None*

Fix local jump on routes

---

config/initializers/main_navigation.rb
config/locales/ca.yml
config/locales/en.yml
config/locales/es.yml
decidim-dataviz/config/locales/ca.yml
decidim-dataviz/config/locales/es.yml
decidim-dataviz/lib/decidim/dataviz/engine.rb

This refactors the accountability menu and conditionally shows it depending on the organization's host.
*None*
*None*
*None*

Conditionally show accountability depending on the organization

---

.travis.yml
app/services/decidim_legacy_routes.rb
spec/routing/redirections_spec.rb

We had some errors when redirecting legacy routes to the new system. I found that we had tests, but somehow they were not running on CI so we didn't notice this was failing 👍 
I've added the app tests to the CI, fixed the redirector and added a new test case to solve the issue on Sentry.
None

Fix legacy routes redirector

---

Gemfile
Gemfile.lock
app/services/census_authorization_handler.rb

Use virtus multiparams to coerce dates instead of relying to custom coercing. Fixes impersonation.
*None*
*None*

Use virtus multiparams to coerce dates

---

app/views/census_authorization/_form.html.erb
spec/factories.rb
spec/features/census_authorization_spec.rb
spec/rails_helper.rb

Fixes the census form to show the proper scopes names in the `select` attribute, instead of showing the IDs
- Fixes #162

Fix scopes in census authorization form

---

app/views/census_authorization/_form.html.erb

Don't display the "Ciutat" district at the census verification form.
- Fixes #170

Ignore city scope in Census form.

---

app/controllers/decidim/accountability/admin/import_results_controller.rb
app/mailers/decidim/accountability/import_mailer.rb
config/locales/ca.yml
config/locales/es.yml

This is a bugfix related with the Mailer introduced to inform about the status of a Results import.
None
None
None
None

Fix locales reference

---

config/locales/assemblies.ca.yml
config/locales/assemblies.es.yml

This changes the "assemblies" to "órganos/òrgans", to reflect the naming of this kind of space's here on Barcelona.
- Fixes #205

Assemblies: change menu and others strings (#205)

---

app/services/decidim/accountability/data_checker.rb
lib/tasks/decidim/accountability/check.rake

This PR implements a reporter that helps comparing the differnet accountability entities with the external system where the data comes from. It uses a CSV with information about scopes, categories, and results, as documented in the Rake task.
The columns of the CSV are:
- PAM/PAD: the scope of the result
- Eje: category
- Linea: subcategory
- Actuacion: parent result
- Project: children result
- ID: the external ID of the result
- Progreso: the percentage of progress
- Peso: weight (this field only applies to projects)

Implement DataChecker to check accountability data

---

Gemfile
Gemfile.lock
config/initializers/secure_headers.rb

Adds CSP headers to prevent XSS attacks. Documentation taken from: https://blog.sqreen.io/integrating-content-security-policy-into-your-rails-applications-4f883eed8f45/
- Related to https://github.com/decidim/decidim/issues/117
*None*
*None*
*None*

Add CSP headers

---

config/routes.rb

For some reason, a default page is missing. This PR adds a redirect to overcome this problem.
None
None

Redirect missing page

---

app/views/census_authorization/_form.html.erb
config/locales/ca.yml
config/locales/es.yml

The census form should only show top level scopes, otherwise we're also showing neighbourhoods.

Fix census form scope list and locales

---

Gemfile.lock

Currently, it is not possible to use OAuth authentication using decidim.barcelona as provider due the bug [#4133](https://github.com/decidim/decidim/issues/4133) which causes to respond with a 500 error if the user has an avatar image in his profile.
Currently this affects logins from https://meta.decidim.org and other comming platforms using decidim.barcelona as OAuth provider.
This incorporates the fix [#4917](https://github.com/decidim/decidim/pull/4917) as a [backport](https://github.com/decidim/decidim/commit/45a62d47fcc007fbcbe1a3e73b2b7bed51fdd04c).

Update decidim commit version to incorporate OAuth fix

---

app/services/census_authorization_handler.rb

If the document number param had the letter in lowercase or upcase the hash would be different.

Make sure we always calculate the authorization unique_id the same way

---

config/initializers/initiatives.rb

By default initiatives will be open during 60 days.
- Related to DECIDIM-31

[CONFIG] Set default_signature_time_period_length = 60.

---

public/consells/horta.html

On Decidim Barcelona we need to integrate with other websites of the City Hall. Regarding the Assemblies feature, we need to put an iframe with all the neighbourhoods (sub assemblies) belonging to a given district (assembly). 
Example of where this would be visible: https://ajuntament.barcelona.cat/horta-guinardo/ca/lajuntament/participacio/consell-de-barri 
As this is not needed for other instances we're planning on making an static HTML with all the iframes so it's better for the developers on barcelona.cat 
We wanted to test this Proof of Concept before we deploy this to the rest of districts.

Adds iframe with all the Consells of Horta District

---

config/initializers/decidim.rb
config/secrets.yml

This PR adds configuration options so decidim-barcelona can be integrated with EtherPad.

Make decidim-barcelona Etherpad configurable.

---

Gemfile
Gemfile.lock
db/schema.rb

Here maps web services also change the way clients authenticate. New accounts can only use
`api_key` authentication whether old accounts used `app_id` and `app_code`.
Geocoder gem changes to the new api since version 1.6.0.

Use geocoder v1.5.2 to stay with old Here maps Api

---

.codeclimate.yml
README.md
app/assets/stylesheets/decidim/email.css

Due to override _email.css_ file to fix email layout, codeclimate acts on this new file and throws an error when executing the tests. To prevent this problem, `email.css` is added in the exclude paths list to exclude test execution, as is done in decidim/decidim.
- Related to #287

Apply clearer background to email header

---

lib/decidim/events/author_event.rb
spec/features/remove_overrides_spec.rb

Override `author_event` in order to solve a bug when sending a new debate notification to admin/users, due to a bad use of a presenter.
- Fixes [DECIDIM-126](https://jira.bcn.cat/browse/DECIDIM-126)

Temporal fix in notifications when create debate events exist

---

Gemfile
Gemfile.lock

To reduce memory footprint `newrelic-rpm` gem is being removed.
This gem is not being used since new-relic is neither being used.

Remove newrelic-rpm gem

---

lib/decidim/events/author_event.rb

We've found that there are more events related to resources that must be controlled in notifications list.
When fixing the case for "created debate" notifications the "inpiring" source code for the override, taken from `coauthorships_cell` was not taking into account other resources that appear in notifications, like official meetings.
- Related to #307
- Fixes #307

Take into account more kinds of resources in author_presenter

---

Gemfile
Gemfile.lock
app.json
config/initializers/decidim.rb
config/secrets.yml

Here maps has deprecated the API that we were currently using via `geocoder` < 1.5. To use the new Here API, we must upgrade to `geocoder` >= 1.6. To keep the gem up to date with security fixes we must upgrade.
This PR upgrades `geocoder` to use Decidim with the new Here API. It also contains the required configuration change for the credentials.

Upgrade geocoder to use the new Here API

---

app/overrides/cells/decidim/proposals/proposal_m_cell_decorator.rb
config/application.rb
spec/features/remove_overrides_spec.rb

We've found that depending on the versions of the PostgreSql database the ordering in which the attachments are returned by the `Attachment` default scope which is:
```ruby
default_scope { order(arel_table[:weight].asc) }
```
for this scope, when all results have the same wight, PostgreSql versions prior to v12 return results finally ordered by `id` DESC. For PostgreSql versions after v12, results having the same weight are finally ordered by `id` but ASC.
Wen the card of a Proposal was checking if the first attachment is an image, it was behaving differently depending on the PostgreSql version.
- Fixes #?

Make finding of first proposal img consistent between postgres versions

---

config/routes.rb
spec/routing/redirections_spec.rb

When browsing to pages of the meetings directory, i.e. `/meetings/meetings?page=2` this url collides with the regacy routes redirects for top-level proposals.
This PR tries to fix this by adding constraints to the false matches.

Avoid meetings directory collision with legacy routes

---

config/routes.rb
spec/routing/redirections_spec.rb

Due to https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/329 routes with the format `assemblies/barrilaprosperitat/f/2559/meetings/3755` were being matched by legacy routes.
This PR refines the regular expression to avoid this situation.
- Related to #329

Refine regexp in legacy routes constraints to avoid false positives

---

app/overrides/cells/decidim/meetings/upcoming_events_cell_decorator.rb
spec/features/remove_overrides_spec.rb

This PR ports the fix in PR #6778 by using decorators while this app is not upgraded to v0.23:
"When there are private meetings marked as non transparent, they are showed on upcoming meetings if the current user is logged. No matters if the user is registered to them."

Fix in upcoming meetings show only visible meetings

---

db/migrate/20201119122917_add_commentable_counter_cache_to_meetings.decidim_meetings.rb

This PR fixes a migration that failed while running the migrations with a backup.

Fix migration

---

Gemfile.lock
app/services/census_authorization_handler.rb
config/initializers/decidim.rb
db/migrate/20210217110107_add_scope_id_to_census_authorizations.rb
db/schema.rb
spec/services/census_authorization_handler_spec.rb

This PR fixes a bug where in some specific cases users couldn't sign initiatives because the authorization metadata was missing a key.
This is in sync with https://github.com/decidim/decidim/pull/7407
None

Add scope_id to census auths

---

config/initializers/decidim_budgets.rb
config/locales/decidim_budgets_workflows_en.yml
lib/budgets_workflow_pam2020.rb

Add the PAM 2020 budgets workflow, allows to Vote in the participant's district and in another of free choice.
⚠️ `Decidim::Budgets.workflows` available on **Decidim 0.23.0**
- Related to https://github.com/decidim/decidim/issues/5711

feat(budgets): add PAM 2020 budgets workflow

---

decidim-ephemeral_participation/lib/tasks/purge_unused_verifications.rake

This PR adds a rake task to delete the authorizations and conflicts (if they exist) for ephemeral users that didn't vote on any budgets process.
- Fixes #?

Add purge unused verifications for ephemeral users task

---

decidim-ephemeral_participation/app/permissions/decidim/ephemeral_participation/ephemeral_participation_permissions.rb

Ephemeral participation module should not intervene in the scope picker modal. This fixes that 
- Fixes #?

fix scope picker permissions

---

app/views/decidim/initiatives/initiative_signatures/fill_personal_data.html.erb
spec/lib/overrides_spec.rb

The responsible declaration text that appears to sign an initiative should show formatted text, and was showing as plain text

text of responsible declaration in initiatives signature fixed

---

app/views/decidim/initiatives/initiative_signatures/fill_personal_data.html.erb
config/locales/ca.yml
config/locales/es.yml

Document number field should have a hint text giving some extra information.
- Related to Decidim-610
- Fixes: Hint text added below document number field and the corresponding translations.

Hint text, Initiative Signatures Form (Document number)

---

config/initializers/redis.rb
config/initializers/sidekiq.rb

Configure Redis to accept messages using a TLS layer required in [Redis 6+ in Heroku](https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-ruby).

Fix Redis TLS configuration

---

config/initializers/sidekiq.rb

Fix error: `ArgumentError (Job arguments to Decidim::EventPublisherJob must be native JSON types` by disabling `strict_args` as specified in the [upgrade notes of Sidekiq 7](https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md#strict-arguments).

Disable strict args for sidekiq

---

app/cells/decidim/meetings/join_meeting_button/show.erb
spec/lib/overrides_spec.rb

Now, the Join meeting button does not ask for to be logged if the meeting registration takes place on another platform.

Join meeting button does not ask for log-in

---

app/cells/concerns/decidim/meetings/online_meeting_cell_override.rb
app/cells/decidim/meetings/online_meeting_link/show.erb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

The videoconference iframe had a 16:9 size, which left part of the iframe content hidden.
- Related to: Decidim-657
- Fixes: Father div of that iframe was resized to 1100px only when the meeting is on live.

Videoconference Iframe resized

---

app/helpers/concerns/decidim/meetings/meetings_helper_override.rb
app/views/decidim/meetings/meetings/_meeting_agenda.html.erb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

When any of the meeting agenda durations is not known, it shows the same time range.
- Related to Decidim-658
- Fixes: Times ranges are now hidden if any of the meeting's agenda times is 0 or any of their sub agenda items.

Hide Meeting duration if zero

---

app/cells/decidim/initiatives/initiative_m/footer.erb
app/models/concerns/decidim/initiative_override.rb
app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

The number of signatures for the scoped type has changed, but it shouldn't affect to older initiatives with this scope. That's why we change these methods here for the old initiatives with this scope created when the number of signatures required was different.
We changed the views too as they called directly to the `Decidim::InitiativesTypeScope` where there is no `Decidim::Initiative` in the context.

Force number of signatures to older initiatives for a scope that changed the number of them

---

app/cells/concerns/decidim/meetings/join_meeting_button_cell_override.rb
config/initializers/decidim_overrides.rb
config/locales/ca.yml
config/locales/en.yml
config/locales/es.yml
spec/lib/overrides_spec.rb

The URL Join meeting and the register meeting buttons were sharing the same translation.
Now they show different ones, and it can easily be overridden through Term Customizer module.
- Related to DECIDIM-729

Meeting buttons translation scope

---

app/packs/stylesheets/_global_accountability.scss
app/views/decidim/accountability/results/_home_categories.html.erb

Fix category style when at least one has children.
- Related to DECIDIM-726
All the categories have children:
One category has children:
No category has children:
No category has children (customization with images):

Show only one category by row

---

app/services/decidim/accountability/results_csv_exporter.rb
spec/services/results_csv_exporter_spec.rb

Fix error on `app/services/decidim/accountability/results_csv_exporter.rb:69`:
```
undefined method `*' for nil:NilClass
```
- Related to [Sentry 1b4199466b9745eab77f0752099d2186](https://decidim-barcelona-q1.sentry.io/issues/3616994705/events/1b4199466b9745eab77f0752099d2186/)

Fix `ResultsCsvExporter` for results with nil weight

---

.codeclimate.yml
app/services/decidim_legacy_routes.rb
config/routes.rb
spec/routing/redirections_spec.rb

The legacy routes redirections weren't updated and they were failing for accountability result components.
- Related to [Sentry 10558c3944d04140880ca168c31a21af](https://decidim-barcelona-q1.sentry.io/issues/1727072047/events/10558c3944d04140880ca168c31a21af/)

Fix legacy routing redirections

---

app/views/decidim/accountability/results/_home_categories.html.erb

After the [migration to `ransack`](https://github.com/decidim/decidim/pull/8748) applied in the 0.27 verstion, a bug appeared in the custom view for home categories in the accountability component as the URL generated to access the results of each category needed a change in the key for the category and scope filters.
- Fixes DECIDIM-757

Fix filter results

---

app/views/decidim/accountability/results/_home_scopes.html.erb

The fix proposed in #491 was not complete. Include the fix for another custom view.
- Related to #491 
- Fixes #493

Fix filter on custom accountability component view

---

app/commands/decidim/admin/publish_component.rb
spec/lib/overrides_spec.rb

Revert [this change](https://github.com/decidim/decidim/pull/10690/files#diff-e2b21b3919dab12185ee7a8e2d0f97b5c5a5666b5bc7ae9baba233b12ebdfaa9) as we want the answers of the component to be cleared when it's (re)published.
- Fixes DECIDIM-754
- Fixes #496

Send publish component notification even when the component is (re)published

---

app/presenters/concerns/decidim/deleted_author_presenter.rb
app/presenters/concerns/decidim/proposals/proposal_presenter_override.rb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

Show "deleted user" when the linked proposal author has been deleted avoiding raising the error described in the below-mentioned issue.
- Fixes #509

Fix error rendering proposals with a linked proposal with deleted author

---

README.md
app/packs/stylesheets/email.scss
spec/lib/overrides_spec.rb

The `email.scss` wasn't in the `spec/lib/overrides_spec.rb` and it was indicated in the README.md that it has some monkey patch applied. In this PR I move this file to the overrides spec and include the missing commits coming from: https://github.com/decidim/decidim/pull/8833 and https://github.com/decidim/decidim/pull/9635

Update email stylesheets and add it to the overrides spec

---

app/lib/decidim/overrides/search_resource_fields_mapper.rb
config/initializers/decidim_overrides.rb
lib/tasks/comments_cleaner.rake
spec/lib/overrides_spec.rb

Add a new task to destroy comments with nil commentable or author. You only need to run:
```bash
bin/rails comments_cleaner:clean
```
- Fixes #515

New comments cleaner task to remove comments with nil reference

---

app/helpers/concerns/decidim/proposals/application_helper_override.rb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb
spec/rails_helper.rb
spec/system/proposal_safe_content_allowed_users_spec.rb

Allow users to use videos in the proposals if they are present in the `PROPOSAL_SAFE_CONTENT_ALLOWED_USERS` environment variable.
- Fixes #537

Allow users to include videos in the proposals

---

app/lib/decidim/overrides/forms/user_answers_serializer.rb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

Fix the order of the column to be the same as the one shown in the admin page (order questions by position)
- Related to #522 
- Fixes #535

Fix column order exporting survey answers on CSV

---

app/controllers/concerns/decidim/admin/conflicts_controller_override.rb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

Remove deleted users from results on the conflicts admin endpoint, so it will take less time to render the page.
A better solution would be include a pagination in this page.

Do not show deleted users on verification conflicts list

---

README.md
lib/tasks/notifications.rake

Rake task to remove old notifications.
- Related to DECIDIM-996

Rake task to remove old notifications

---

config/secrets.yml
config/storage.yml

The previous configuration was not working as expected as it returned `true` every time an environment variable `AWS_PUBLIC` existed, ignoring its value.
This configuration will only include the line `public: true` in the `s3` storage configuration if the environment variable exists and the value is different than `0`, `false`, or `no`.
- Related to https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/579

Fix S3 public bucket configuration

---

app/views/decidim/proposals/index.html.erb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb
spec/system/assemblies_spec.rb

- Paginate by 10 elements by default
- Remove map from the index page of the proposals component

Proposal index page performance improvements

---

Gemfile.lock

Bump `decidim-internal_evaluation` module including a backport
- Related to https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/pull/14

Bump `decidim-internal_evaluation` module

---

app/services/timestamp_service.rb
package.json

AOC is returning an `SSL certificate problem: certificate has expired` error when we request that they create a signature. We are disabling SSL verification temporarily while they fix the error on their side. 
We must create an environment variable `TIMESTAMP_SERVICE_SKIP_SSL=true` to enable this. Otherwise, it will work as before.

Allow non-SSL connection with timestamp service

---

Gemfile.lock

Bump decidim version including a official backport
- Related to https://github.com/decidim/decidim/pull/13956

Bump decidim version from `efc37d1` to `6836a27`

---

lib/tasks/sanitize_nicknames.rake

There are some existing users with nicknames with invalid characters. Every time something changes in the user, the save method is failing so those users are kind of broken. With the `decidim:sanitize_nicknames` task we will be able to sanitize the nickname for the users with invalid characters on it. We will need some manual actions if the sanitized nicknames is being already used by other users.
- Related to DECIDIM-1045

Create task to sanitize nicknames

---

config/database.yml

The `DATABASE_POOL` was being ignored in the production environment.

Allow to configure database pool in production

---

Gemfile
Gemfile.lock

Bump `decidim-decidim_awesome` version as the branch `upgrade-0.29` has been deleted after merging it into `main`.

Bump `decidim-decidim_awesome` version

---

app/helpers/concerns/decidim/accountability/application_helper_override.rb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

During the redesign of Decidim performed in v0.28, some of the views were changed, and some methods became unused. They were deleted in v0.29, but we still have some overridden views using them, so we need to restore them to avoid exceptions while loading some pages.
- Related to https://github.com/decidim/decidim/pull/12698
- Related to https://github.com/decidim/decidim/pull/12853

Restore deleted methods by decidim used in overridden views

---

Gemfile
Gemfile.lock
config/initializers/wicked_pdf.rb

Fixes the error below
```
ActionView::Template::Error uninitialized constant WickedPdf::WickedPdfHelper::Assets::SprocketsEnvironment::Sprockets 
```
- Related to https://github.com/mileszs/wicked_pdf/issues/1102
- Related to https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/615

Downgrade `wicked_pdf` from 2.8.0 to 2.7.0

---

config/locales/ca.yml
config/locales/es.yml

While doing UX testing, we found out two mini bugs with the budgets summary after voting;
- There's a missing string interpolation (`%{cancel_link}`)
- The message in the button is too large
This PR fixes them by removing the overrides and using the default values from upstream (decidim defaults)
. Sign in as user
. Vote in a budgets component
. See the summary after voting

Remove overrides for budget summary messages

---

app/cells/concerns/decidim/system/system_checks_cell_override.rb
app/forms/concerns/decidim/system/base_organization_form_override.rb
config/initializers/decidim_overrides.rb
spec/lib/overrides_spec.rb

The `secret_key_base` size we have in our server does not match with the size proposed by decidim. Instead of changing it, we change the expected size in the validations, so we will be able to update an organization from the system page again.

Fix `secret_key_base size` validation

---

Gemfile.lock

Bump decidim version including the `nicknamize` method mandatory parameter backport: https://github.com/decidim/decidim/pull/14683

Bump decidim version from `d518932` to `18b810a`

---

config/initializers/decidim.rb

In https://github.com/decidim/decidim/pull/14180, we transitioned from version v1 to version v3 of Here Maps. However, the default URL in the initializer was not modified. To address this issue, we can define the `MAPS_STATIC_URL` environment variable. However, to facilitate maintenance, we have modified the default URL in the initializer as specified in the release notes: https://github.com/decidim/decidim/releases/tag/v0.29.3
- Related to DECIDIM-1115

Fix default static here maps URL

---

app/models/concerns/decidim/accountability/result_override.rb
spec/factories.rb
spec/models/decidim/accountability/result_spec.rb

In this decidim instance we have a database unique index for `external_id` and `decidim_component_id` in the `decidim_accountability_results` table. That was causing an error when we have two `Decidim::Accountability::Result` records with repeated external ids for the same component.
We don't know exactly how, (maybe a one-time action of a previous Decidim upgrade) but we had several external ids with an empty string instead of a null, raising the exception described above.
With this solution, we'll avoid this situation as every time we save a `Decidim::Accountability::Result` record, we'll check if the `external_id` is empty converting it into a null value instead.
- Related to DECIDIM-1169

Avoid having empty external ids on accountability results
